[tool.poetry]
name = "mac-music-util"
version = "0.1.0"
description = ""
authors = ["shu <shu@ceshmina.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mutagen = "^1.46.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
